account/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import patterns, url

__author__ = 'denis'


urlpatterns = patterns(
    'account.views',
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^register/$', 'register', name='register')
)

guest/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^', include('guestbook.urls', namespace='guestbook')),
]

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

    urlpatterns += staticfiles_urlpatterns()

guestbook/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from .views import IndexView, GuestBookDetail, GuestBookCreate

__author__ = 'denis'


urlpatterns = patterns(
    'guestbook.views',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^add/$', GuestBookCreate.as_view(), name='guestbook_add'),
    url(r'^post/(?P<post_id>\d+)/moderate/$', 'moderate_post', name='moderate_post'),
    url(r'^post/(?P<post_id>\d+)/delete/$', 'delete_post', name='delete_post'),
    url(r'^(?P<slug>[^\.]+)/$', GuestBookDetail.as_view(), name='guestbook'),
)

guestbook/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models

__author__ = 'denis'


class GuestBook(models.Model):
    class Meta:
        verbose_name = 'Гостевая книга'
        verbose_name_plural = 'Гостевые книги'

    title = models.CharField(max_length=256, verbose_name='Название', unique=True)
    slug = models.SlugField(max_length=256, verbose_name='Ссылка', unique=True)
    pre_approval = models.BooleanField(default=False, verbose_name='Модерировать посты')
    user = models.ForeignKey(to='auth.User', verbose_name='Пользователь')
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)

    @models.permalink
    def get_absolute_url(self):
        return 'guestbook:guestbook', None, {'slug': self.slug}

    def __unicode__(self):
        return self.title


class Post(models.Model):
    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created', )

    username = models.CharField(max_length=128, verbose_name='Имя')
    text = models.TextField(verbose_name='Текст')
    guestbook = models.ForeignKey(to='guestbook.GuestBook', verbose_name=u'Гостевая книга')
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    moderated = models.BooleanField(default=False)

    def __unicode__(self):
        return self.username

guestbook/views.py
# coding=utf-8
from __future__ import unicode_literals
from annoying.functions import get_object_or_None
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView
from guestbook.models import GuestBook, Post

__author__ = 'denis'


class IndexView(ListView):
    model = GuestBook


class GuestBookCreate(CreateView):
    model = GuestBook
    fields = ('user', 'title', 'slug', 'pre_approval')

    @method_decorator(login_required(login_url='account:login'))
    def dispatch(self, *args, **kwargs):
        return super(GuestBookCreate, self).dispatch(*args, **kwargs)

    def get_initial(self):
        init = super(GuestBookCreate, self).get_initial()
        init['user'] = self.request.user.id
        return init
    
    def get_form_kwargs(self):
        form_kwargs = super(GuestBookCreate, self).get_form_kwargs()
        if self.request.method in ('POST', 'PUT'):
            fake_post = self.request.POST.copy()
            fake_post['user'] = self.request.user.id
            form_kwargs['data'] = fake_post
        return form_kwargs


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('username', 'text', 'guestbook')


class GuestBookDetail(DetailView):
    model = GuestBook

    def get_context_data(self, **kwargs):
        context = super(GuestBookDetail, self).get_context_data(**kwargs)

        data = {}
        if self.request.method == 'POST':
            data = self.request.POST.copy()
            data['guestbook'] = self.object.id

        initial = {'username': self.request.user.username if self.request.user.is_authenticated() else ''}
        form = PostForm(data or None, initial=initial)
        if form.is_valid():
            form.save()
            context['success'] = self.object.pre_approval
            form = PostForm()
        context['post_form'] = form

        posts = Post.objects.filter(guestbook=self.object)
        auth_user = self.request.user.is_authenticated()
        if not auth_user and self.object.pre_approval:
            posts = posts.filter(moderated=True)
        if self.object.pre_approval and auth_user and self.object.user_id != self.request.user.id:
            posts = posts.filter(moderated=True)
        context['posts'] = posts

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


@login_required(login_url='account:login')
def moderate_post(request, post_id):
    post = get_object_or_None(Post.objects.select_related('guestbook'), id=post_id)
    if not post:
        return redirect(request.META.get('HTTP_REFERER', 'guestbook:index'))
    if post.guestbook.user_id != request.user.id:
        return redirect(request.META.get('HTTP_REFERER', post.guestbook.get_absolute_url()))
    post.moderated = True
    post.save()
    return redirect(post.guestbook.get_absolute_url())


@login_required(login_url='account:login')
def delete_post(request, post_id):
    post = get_object_or_None(Post.objects.select_related('guestbook'), id=post_id)
    if not post:
        return redirect(request.META.get('HTTP_REFERER', 'guestbook:index'))
    if post.guestbook.user_id != request.user.id:
        return redirect(request.META.get('HTTP_REFERER', post.guestbook.get_absolute_url()))
    url = post.guestbook.get_absolute_url()
    post.delete()
    return redirect(url)

guestbook/templates/guestbook/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <style>
        body {
          padding-top: 50px;
        }
        .starter-template {
          padding: 40px 15px;
        }
    </style>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
    {% include 'guestbook/main_menu.html' %}
    <div class="container">
      <div class="starter-template">
        {% block content %}{% endblock %}
      </div>
    </div>
</body>
</html>

guestbook/templates/guestbook/guestbook_detail.html
{% extends 'guestbook/base.html' %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
    <h1>{{ object.title }}</h1>
    <form method="post" class="form-horizontal" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Имя:</label>
            <input type="text" name="username" id="id_username" class="form-control" value="{% if user.is_authenticated %}{{ user.username }}{% endif %}"/>
            {{ post_form.username.errors }}
        </div>
        <div class="form-group">
            <label for="id_text">Текст:</label>
            <textarea name="text" id="id_text" class="form-control" cols="30" rows="10"></textarea>
            {{ post_form.text.errors }}
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-default" value="Добавить сообщение"/>
        </div>
    </form>
    {% if success %}<div class="alert alert-info">Ваше сообщение добавлено и появится сразу после модерации</div>{% endif %}
    {% for post in posts %}
        <div class="panel panel-default">
          <div class="panel-heading">Автор: <i>{{ post.username }}</i>&nbsp;Дата: <i>{{ post.created }}</i></div>
          <div class="panel-body">
            {{ post.text }}
            {% if not post.moderated and post.guestbook.user_id == user.id %}
                <div>
                    <span>
                        <a href="{% url 'guestbook:moderate_post' post_id=post.id %}">Опубликовать</a>
                    </span>&nbsp;&nbsp;&nbsp;
                    <span>
                        <a href="{% url 'guestbook:delete_post' post_id=post.id %}">Удалить</a>
                    </span>
                </div>
            {% endif %}
          </div>
        </div>
    {% empty %}
        <div class="alert alert-info">Еще никто ничего не написал.</div>
    {% endfor %}
{% endblock %}

guestbook/templates/guestbook/guestbook_form.html
{% extends 'guestbook/base.html' %}
{% load static %}
{% block title %}Добавление гостевой книги{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'admin/js/urlify.js' %}"></script>
{% endblock %}
{% block content %}
    <h1>Добавить гостевую книгу</h1>
    <form method="post" class="form-horizontal" >
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Название:</label>
            <input type="text" name="title" class="form-control" id="id_title"/>
            {{ form.title.errors }}
        </div>
        <div class="form-group">
            <label for="id_slug">Ссылка:</label>
            <input type="text" name="slug" class="form-control" id="id_slug"/>
            {{ form.slug.errors }}
        </div>
        <div class="form-group">
            <label for="id_pre_approval">Модерировать посты:</label>
            {{ form.pre_approval }}
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-default" value="Создать"/>
        </div>
    </form>
    <script type="text/javascript">
        document.getElementById("id_title").onkeyup = function() {
            var e = document.getElementById("id_slug");
            if (!e._changed) { e.value = URLify(document.getElementById("id_title").value, 50); }
        }
    </script>
{% endblock %}

guestbook/templates/guestbook/guestbook_list.html
{% extends 'guestbook/base.html' %}
{% block title %}Сервис гостевых книг{% endblock %}
{% block content %}
    <ul>
        {% for guestbook in object_list %}
            <li><a href="{{ guestbook.get_absolute_url }}">{{ guestbook.title }}</a></li>
        {% empty %}
            <li>Не найдено ни одной гостевой книги</li>
        {% endfor %}
    </ul>
{% endblock %}

guestbook/templates/guestbook/main_menu.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand active" href="/">Сервис гостевых книг</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
            <li><a href="{% url 'guestbook:guestbook_add' %}">Добавить новую гостевую книгу</a></li>
            <li><a href="{% url 'account:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'account:login' %}">Войти</a></li>
            <li><a href="{% url 'account:register' %}">Зарегистрироваться</a></li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ user.username }}</a></li>
        </ul>
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</div>